### PR TITLE
jx step stash

### PR DESCRIPTION
**Pull request by jglick**
Does [this](https://jenkins-x.io/architecture/storage/#using-stash) work?

### CODE REVIEW

**Comment by cd-process** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **jglick**

If they are not already assigned, you can assign the PR to them by writing `/assign @jglick` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/cb-kubecd/vertx-demo/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by cd-process** [comment]
@jglick: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | 8fe1e8d9126857fdb48758ea893de000c5fd4792 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by cd-process** [comment]
:star: PR built and available in a preview environment **cb-kubecd-vertx-demo-pr-18** [here](http://vertx-demo.jx-cb-kubecd-vertx-demo-pr-18.dev.cd-process.com)

**Comment by cd-process** [comment]
:star: PR built and available in a preview environment **cb-kubecd-vertx-demo-pr-18** [here](http://vertx-demo.jx-cb-kubecd-vertx-demo-pr-18.dev.cd-process.com)

**Comment by cd-process** [comment]
:star: PR built and available in a preview environment **cb-kubecd-vertx-demo-pr-18** [here](http://vertx-demo.jx-cb-kubecd-vertx-demo-pr-18.dev.cd-process.com)

**Comment by cd-process** [comment]
:star: PR built and available in a preview environment **cb-kubecd-vertx-demo-pr-18** [here](http://vertx-demo.jx-cb-kubecd-vertx-demo-pr-18.dev.cd-process.com)

**Comment by jglick** [comment]
/meow space

’cuz I need to know.

**Comment by cd-process** [comment]
@jglick: [cat image](https://thecatapi.com/?image_id=53)

<details>

In response to [this](https://github.com/cb-kubecd/vertx-demo/pull/18#issuecomment-457657590):

>/meow space
>
>’cuz I need to know.


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by cd-process** [comment]
@jglick: [cat image](https://thecatapi.com/?image_id=h4)

<details>

In response to [this](https://github.com/cb-kubecd/vertx-demo/pull/18#issuecomment-459001259):

>/meow


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by cd-process** [comment]
@jglick: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | 200d1e2e070e58a36c01df9cfac5f90d75978dcd | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by jglick** [comment]
```
[ERROR] Non-resolvable import POM: Could not transfer artifact io.vertx:vertx-dependencies:pom:3.5.1 from/to nexus (http://nexus/repository/maven-group/): Not authorized , ReasonPhrase:Unauthorized. @ line 25, column 25
```

**Comment by cd-process** [comment]
:star: PR built and available in a preview environment **cb-kubecd-vertx-demo-pr-18** [here](http://vertx-demo.jx-cb-kubecd-vertx-demo-pr-18.dev.cd-process.com)

**Comment by cd-process** [comment]
:star: PR built and available in a preview environment **cb-kubecd-vertx-demo-pr-18** [here](http://vertx-demo.jx-cb-kubecd-vertx-demo-pr-18.dev.cd-process.com)

**Comment by cd-process** [comment]
:star: PR built and available in a preview environment **cb-kubecd-vertx-demo-pr-18** [here](http://vertx-demo.jx-cb-kubecd-vertx-demo-pr-18.dev.cd-process.com)

**Comment by cd-process** [comment]
@jglick: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | 64a7d3db059051db345670cf7be8f779355e8114 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
